name: Backend CI with Gradle

on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Create .env file
        run: |
          cat <<EOF > .env
          STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
          S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
          S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          EOF

      - name: Build with Gradle
        run: |
          cd backend/
          ./gradlew build --info